<a href="https://colab.research.google.com/github/Lukas-Swc/machine-learning-bootcamp/blob/main/unsupervised/02_dimensionality_reduction%20/03_pca_wine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### scikit-learn
Strona biblioteki: [https://scikit-learn.org](https://scikit-learn.org)  

Dokumentacja/User Guide: [https://scikit-learn.org/stable/user_guide.html](https://scikit-learn.org/stable/user_guide.html)

Podstawowa biblioteka do uczenia maszynowego w języku Python.

Aby zainstalować bibliotekę scikit-learn, użyj polecenia poniżej:
```
!pip install scikit-learn
```
Aby zaktualizować do najnowszej wersji bibliotekę scikit-learn, użyj polecenia poniżej:
```
!pip install --upgrade scikit-learn
```
Kurs stworzony w oparciu o wersję `0.22.1`

### Spis treści:
1. [Import bibliotek](#0)
2. [Załadowanie danych](#1)
3. [Podział na zbiór treningowy i testowy](#2)
4. [Standaryzacja](#3)
5. [PCA](#4)



### <a name='0'></a> Import bibliotek

In [1]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px

np.set_printoptions(precision=4, suppress=True, edgeitems=5, linewidth=200)

### <a name='1'></a> Załadowanie danych

In [2]:
df_raw = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data', header=None)
df = df_raw.copy()
df.head()

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [3]:
data = df.iloc[:, 1:]
target = df.iloc[:, 0]
data.head()

1     2     3     4    5     6     7     8     9     10    11    12  \
0  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [4]:
target.value_counts()

0
2    71
1    59
3    48
Name: count, dtype: int64

### <a name='2'></a> Podział na zbiór treningowy i testowy

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target)

print(f'X_train shape: {X_train.shape}')
print(f'X_test shape: {X_test.shape}')

X_train shape: (133, 13)
X_test shape: (45, 13)


### <a name='3'></a> Standaryzacja

In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)
X_train_std[:5]

array([[ 1.4154, -0.6347,  0.4639, -0.9321,  0.5858,  1.5867,  1.9442, -0.2701,  0.4667,  1.5714,  1.1492,  0.2741,  2.8768],
       [ 1.4644, -0.5328,  0.2807, -1.2154,  2.0173,  0.7927,  1.0486, -0.5998,  1.2144,  0.2377,  0.3193,  1.816 ,  0.9611],
       [-1.9319,  1.19  , -1.9544,  0.0121,  0.5104,  1.3962,  0.5545, -0.9294,  3.4576, -0.9565, -0.9473,  0.2601, -0.6058],
       [-0.387 , -0.4479, -0.562 , -0.2082, -1.0718, -0.1601,  0.503 , -0.7646,  0.3102, -0.5207,  0.8434,  0.7227, -0.1323],
       [-1.7357, -0.2952, -0.2689, -0.46  , -0.1677,  1.1421,  0.2251, -1.5063, -0.4201, -0.8039,  0.8434,  0.4704, -1.2817]])

### <a name='4'></a> PCA

In [7]:
from sklearn.decomposition import PCA

pca = PCA(n_components=3)
X_train_pca = pca.fit_transform(X_train_std)
X_test_pca = pca.transform(X_test_std)
X_train_pca.shape

(133, 3)

Wyjasniona wariancja

In [10]:
results = pd.DataFrame(data={'explained_variance_ratio': pca.explained_variance_ratio_})
results['cumulative'] = results['explained_variance_ratio'].cumsum()
results['component'] = results.index + 1
results

explained_variance_ratio  cumulative  component
0                  0.367886    0.367886          1
1                  0.204488    0.572374          2
2                  0.105677    0.678050          3

In [11]:
fig = go.Figure(data=[go.Bar(x=results['component'], y=results['explained_variance_ratio'], name='explained variance ratio'),
                      go.Scatter(x=results['component'], y=results['cumulative'], name='cumulative explained variance')],
                layout=go.Layout(title=f'PCA - {pca.n_components_} components', width=950, template='plotly_dark'))
fig.show()

In [12]:
X_train_pca_df = pd.DataFrame(data=np.c_[X_train_pca, y_train], columns=['pca1', 'pca2', 'pca3', 'target'])
X_train_pca_df.head()

pca1      pca2      pca3  target
0  3.540746  2.290521 -0.459530     1.0
1  3.325521  1.365453 -0.280022     1.0
2  1.362824 -1.407473  0.273246     2.0
3  0.907818 -1.543695 -0.143462     2.0
4  0.834128 -2.171281  0.105861     2.0

In [13]:
px.scatter_3d(X_train_pca_df, x='pca1', y='pca2', z='pca3', color='target', template='plotly_dark', width=950)

In [14]:
X_train_pca[:5]

array([[ 3.5407,  2.2905, -0.4595],
       [ 3.3255,  1.3655, -0.28  ],
       [ 1.3628, -1.4075,  0.2732],
       [ 0.9078, -1.5437, -0.1435],
       [ 0.8341, -2.1713,  0.1059]])

In [15]:
X_test_pca[:5]

array([[ 1.9125, -1.9993,  0.2056],
       [-2.469 ,  2.1379, -0.8126],
       [-3.5973,  1.3445, -0.0399],
       [ 0.6378, -1.3647,  1.1773],
       [ 1.7153,  0.5502,  0.0319]])